### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by EduardvonBriesen** [EduardvonBriesen/mememuc#12]
Here, you should implement some possibility for the user to identify themselves, e.g., the user can always upload under the same username.

1. **Basic**: Anything that does the above. Does not need to be secure, i.e., it is okay if users could upload under a different name. 
2. **Intermediate**: Make it secure, i.e., require a password to login with a specific username/email address.
3. **Advanced**: Integrate a third party service(s) to authenticate users, e.g., google/Facebook/steam/etc.

**Comment by EduardvonBriesen** [comment]
https://www.passportjs.org/

**Comment by EduardvonBriesen** [comment]
Target: Advanced

**Comment by IIShortyII** [comment]
1. Registration
2. New User in DB anlegene
3. Authentification methods
