### ISSUE TITLE
Canvas and Images

### ISSUE THREAD

**Issue by EduardvonBriesen** [EduardvonBriesen/mememuc#3]
1. **Basic**: none
2. **Intermediate**: The user can append other images (from a set of templates or upload, etc.) left, right, top, or bottom from the current meme. Aspect ratio of the original and the added image should be conserved.
3. **Advanced**: You can freely adjust the canvas size and place images anywhere inside the canvas.

**Comment by EduardvonBriesen** [comment]
Target: Advanced

**Comment by lieutenant-linse** [comment]
ToDo: Option to unlock the free canvas
