### ISSUE TITLE
Generation and Download

### ISSUE THREAD

**Issue by EduardvonBriesen** [EduardvonBriesen/mememuc#4]
By default the generated meme should be added to the website. Additionally the creator receives
immediate feedback.

1. **Basic**: The finished meme is generated and shown to the user. 
2. **Intermediate**: The user can choose to either create the meme locally on their device or on the webserver. Afterwards they are shown the image and provided with a download button.
3. **Advanced**: In addition to intermediate, the user can specify a target file-size before the image creating and share buttons are presented below the image. The generated meme should have the specified (or lower) file-size. Providing a button that copies the “singleview-URL” of the image into the clipboard suffices as a share button.

--------------------------------------------------------------------------------------------------------------------------------

- [x] Add database structure for saved memes
- [x] Add button for generating memes
- [x] Generate meme as .png (?) and show it to user (-> SingleView?)
- [x] Save meme to database
- [ ] give user option to choose to either create the meme locally on their device or on the webserver (???)
- [ ] Provide user with download button (Where? directly or in SingleView?)
- [ ] Let user specify file-size when generating
- [ ] Add share button

**Comment by EduardvonBriesen** [comment]
Target: Advanced

**Comment by EduardvonBriesen** [comment]
Edit meme on on webserver unclear...

**Comment by lieutenant-linse** [comment]
closed: give user option to choose to either create the meme locally on their device or on the webserver 

Now possible via Enpoint "Create" in meme.ts
