### ISSUE TITLE
Single View

### ISSUE THREAD

**Issue by EduardvonBriesen** [EduardvonBriesen/mememuc#9]
This should be the detail view for a meme, including detailed information, comments, option to add comments, etc. It can also contain left right buttons to go through the memes or an auto play button. Each meme should have a dedicated URL that opens that meme in single view. Instead of a dedicated page, you can show this as a layer over the Overview.

1. **Basic**: A simple slide show with left/right buttons.
2. **Intermediate**: Basic with an added random button, which jumps to any randomly selected meme.
3. **Advanced**: Intermediate, with an added autoplay button. Activating this button displays a new meme every x seconds (either choose a fix number or let the user choose x).

depends on #15 

---------------------------------------------------------------------------------------------------------------------------------------

- [ ] Left/ right buttons Slideshow
- [ ] Random Button
- [ ] Autoplay button
- [ ] Let user choose title
- [ ] update quality prompt

**Comment by EduardvonBriesen** [comment]
Target: Advanced

**Comment by uzerterter** [comment]
Should implement the following from Ticket #4 :
- [ ] give user option to choose to either create the meme locally on their device or on the webserver (???) (before singleview?)
- [ ] Provide user with download button (Where? directly or in SingleView?)
- [ ] Let user specify file-size when generating
- [ ] Add share button
